spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rental_hub?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 712803!felipe
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  application:
    name: RentalHubAPI